import turtle
Kalem = turtle.Turtle()

Kalem.speed(3)
Kalem.color("red")
Kalem.width(8)

Kalem.circle(40)
Kalem.right(90)
Kalem.forward(30)
Kalem.right(50)
Kalem.forward(60)
Kalem.backward(60)
Kalem.left(50)
Kalem.forward(60)
Kalem.forward(20)
Kalem.right(50)
Kalem.forward(60)
Kalem.backward(60)
Kalem.left(100)
Kalem.forward(60)
Kalem.backward(60)
Kalem.left(130)
Kalem.forward(75)
Kalem.right(130)
Kalem.forward(60)

Kalem.backward(60)
Kalem.right(50)
Kalem.forward(15)

Kalem.forward(64)
Kalem.color("blue")
Kalem.right(50)
Kalem.forward(60)
Kalem.backward(60)
Kalem.left(100)
Kalem.forward(60)
Kalem.color("black")
Kalem.left(40)
Kalem.forward(300)
Kalem.backward(8000)

